var ojx={menu:0,init:function(){ojx.href=document.location.href;ojx.lang="en";-1!=(navigator.language||navigator.browserLanguage).indexOf("de")&&(ojx.lang="de");-1!=ojx.href.indexOf("ojlangde")&&(ojx.lang="de");-1!=ojx.href.indexOf("ojlangen")&&(ojx.lang="en");-1!=ojx.href.indexOf("ojlangja")&&(ojx.lang="ja");var a="Android;iPhone;iPad;iPod;PlayBook;Kindle;Blackberry;webOS;Windows Phone;IEMobile;Opera Mini;Opera Mobi".split(";");ojx.mobile=!1;for(var b=0;b<a.length;b++)-1!=navigator.userAgent.indexOf(a[b])&&
(ojx.mobile=!0);-1!=ojx.href.indexOf("ojmob")&&(ojx.mobile=!0);-1!=ojx.href.indexOf("ojpwa")||window.matchMedia("(display-mode: standalone)").matches?ojx.app=ojx.pwa=!0:-1!=ojx.href.indexOf("ojapps")?ojx.app=ojx.apps=!0:-1!=ojx.href.indexOf("ojappt")?ojx.app=ojx.appt=!0:-1!=ojx.href.indexOf("ojapp")&&(ojx.app=!0);if(ojx.mobile)if(410>=screen.width||410>=screen.height)ojx.app=ojx.apps=!0;else if(610>=screen.width||610>=screen.height)ojx.app=ojx.appt=!0;ojx.app||(ojx.web=!0);ojx.ua=navigator.userAgent;
ojx.msie=-1!=ojx.ua.indexOf("MSIE");ojx.edge=-1!=ojx.ua.indexOf("Edge");ojx.opera=-1!=ojx.ua.indexOf("Opera");ojx.chrome=-1!=ojx.ua.indexOf("Chrome");ojx.safari=-1!=ojx.ua.indexOf("Safari")&&-1==ojx.ua.indexOf("Chrome");ojx.firefox=-1!=ojx.ua.indexOf("Firefox");ojx.ios=ojx.ua.match(/(iPad|iPhone|iPod)/i)?!0:!1;ojx.win=-1!=ojx.ua.indexOf("Windows");ojx.mac=-1!=ojx.ua.indexOf("Mac");ojx.android=-1!=ojx.ua.indexOf("Android")}};ojx.init();
ojx.onBody=function(){var a=document.body;a&&!ojx.body&&(ojx.body=!0,"en"==ojx.lang&&a.classList.add("en"),"de"==ojx.lang&&a.classList.add("de"),ojx.ios&&a.classList.add("ios"),ojx.win&&a.classList.add("win"),ojx.mac&&a.classList.add("mac"),ojx.android&&a.classList.add("android"),ojx.msie&&a.classList.add("msie"),ojx.edge&&a.classList.add("edge"),ojx.opera&&a.classList.add("opera"),ojx.chrome&&a.classList.add("chrome"),ojx.safari&&a.classList.add("safari"),ojx.firefox&&a.classList.add("firefox"),
ojx.mobile&&a.classList.add("mobile"),ojx.pwa&&a.classList.add("pwa"),ojx.web&&a.classList.add("web"),ojx.app&&a.classList.add("app"),ojx.apps&&a.classList.add("apps"),ojx.appt&&a.classList.add("appt"),window.self!==window.top&&document.body.classList.add("framed"))};ojx.onBody();
ojx.onLoad=function(){var a=document.location.href;ojx.onBody();var b=document.getElementById("js-required");b&&ojx.hide(b);(b=document.getElementById("index-0"))&&ojx.initTabs("index","index");(b=document.getElementById("rules-0"))&&ojx.initTabs("rules","index");(b=document.getElementById("tab-0"))&&ojx.initTabs("tab","tab");(b=document.getElementById("menu-0"))&&ojx.initMenu("menu");ojx.mobile&&!ojx.ios&&ojx.swipeinit(null,"prev1","next1");-1==a.indexOf("Retros")&&-1==a.indexOf("Schach")||ojx.hideAll("solution");
-1!=a.indexOf("Raetsel")&&ojx.hideSol();-1!=window.location.href.indexOf("ojintern")&&ojx.showAll("intern");if(b=document.getElementById("solb"))b.name=b.href,b.href="javascript:ojx.showSolution();",b.target="";ojx.resizeAllFramesDelayed()};ojx.onResize=function(){ojx.resizeAllFrames()};
ojx.resizeAllFrames=function(){try{for(var a=document.getElementsByTagName("iFrame"),b=0;b<a.length;++b){var c=a[b],d=null;c&&(d=c.contentDocument?c.contentDocument.documentElement:c.contentWindow.document.body)&&(c.style.height="10px",c.style.height=d.scrollHeight+5+"px")}}catch(e){}};ojx.resizeAllFramesDelayed=function(){setTimeout("ojx.resizeAllFrames()",10);setTimeout("ojx.resizeAllFrames()",30);setTimeout("ojx.resizeAllFrames()",50)};
ojx.tr=function(a){location.href="https://translate.google.com/translate?u="+escape(location.href)+"&sl=auto&tl="+a+"&amp;ie="+(document.charset||document.characterSet)};
ojx.trframe=function(a){var b=location.href,c=b.lastIndexOf("/");b=-1!=b.indexOf("/Sudoku/")?"https://www.janko.at/Raetsel/Sudoku/Bedienung.htm":-1!=b.indexOf("/Tapa/")?"https://www.janko.at/Raetsel/Tapa/Bedienung.htm":b.substr(0,c+1)+"Bedienung.htm";window.open("https://translate.google.com/translate?u="+escape(b)+"&sl=auto&tl="+a,"_blank").focus()};ojx.getCookie=function(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;c++)if(-1!=b[c].indexOf(a))return b[c].split("=")[1];return null};
ojx.setCookie=function(a,b,c){var d="";c&&(d=new Date,d.setTime(d.getTime()+864E5*c),d="; expires="+d.toGMTString());document.cookie=a+"="+b+d+"; path=/"};ojx.delCookie=function(a){ojx.setCookie(a,"",-1)};ojx.addEventHandler=function(a,b){window.addEventListener?window.addEventListener(a,b,!1):window.attachEvent&&window.attachEvent("on"+a,b)};ojx.addEventHandler("load",ojx.onLoad);ojx.addEventHandler("resize",ojx.onResize);ojx.show=function(a){a&&(a.style.display="SPAN"==a.tagName?"inline":"block")};
ojx.hide=function(a){a&&(a.style.display="none")};ojx.toggle=function(a){a&&("none"==a.style.display?ojx.show(a):ojx.hide(a))};ojx.isVisible=function(a){return 0<a.offsetWidth&&0<a.offsetHeight};ojx.showOne=function(a){ojx.show(document.getElementById(a))};ojx.hideOne=function(a){ojx.hide(document.getElementById(a))};ojx.toggleOne=function(a){ojx.toggle(document.getElementById(a))};ojx.showAll=function(a){for(var b=document.getElementsByTagName("*"),c=0;c<b.length;c++)b[c].className==a&&ojx.show(b[c])};
ojx.hideAll=function(a){for(var b=document.getElementsByTagName("*"),c=0;c<b.length;c++)b[c].className==a&&ojx.hide(b[c])};ojx.toggleAll=function(a){for(var b=document.getElementsByTagName("*"),c=0;c<b.length;c++)b[c].className==a&&ojx.toggle(b[c])};ojx.showSol=function(){for(var a=document.body.getElementsByTagName("*"),b=0;b<a.length;b++)"sol"==a[b].className.substr(0,3)&&ojx.show(a[b])};
ojx.hideSol=function(){for(var a=document.body.getElementsByTagName("*"),b=0;b<a.length;b++)"sol"==a[b].className.substr(0,3)&&ojx.hide(a[b])};ojx.toggleSol=function(){var a=document.getElementById("sol"),b=a.innerHTML;-1!=b.indexOf("anzeigen")?ojx.showSol():ojx.hideSol();-1!=b.indexOf("anzeigen")?a.innerHTML=b.replace("anzeigen","verbergen"):a.innerHTML=b.replace("verbergen","anzeigen")};
ojx.showHint=function(){for(var a=document.body.getElementsByTagName("*"),b=0;b<a.length;b++)"hint"==a[b].className.substr(0,4)&&ojx.show(a[b])};ojx.hideHint=function(){for(var a=document.body.getElementsByTagName("*"),b=0;b<a.length;b++)"hint"==a[b].className.substr(0,4)&&ojx.hide(a[b])};
ojx.toggleHint=function(){var a=document.getElementById("hint"),b=a.innerHTML;-1!=b.indexOf("anzeigen")?ojx.showHint():ojx.hideHint();-1!=b.indexOf("anzeigen")?a.innerHTML=b.replace("anzeigen","verbergen"):a.innerHTML=b.replace("verbergen","anzeigen")};ojx.tocClass="toc";ojx.tocDiv="toc";ojx.tocHid="toc";
ojx.toc=function(a,b){a||(a=1);b||(b=6);for(var c="",d=1,e=document.querySelectorAll("h1, h2, h3, h4, h5, h6"),g=0;g<e.length;g++){var f=e[g].tagName.substring(1,2);if(f>=a&&f<=b){var h=ojx.tocHid+d;e[g].id&&(h=e[g].id);c+='<p class="'+ojx.tocClass+f+'"><a href=#'+h+">"+e[g].innerHTML+"</a></p>\n";e[g].id||(e[g].id=ojx.tocHid+d++)}}(a=document.getElementById(ojx.tocDiv))?a.innerHTML=c:document.write(c)};
ojx.showSolution=function(a){var b=document.getElementById("solb"),c=0,d=0;a=new Image;a.src=b.name;c=a.width;d=a.height;a.onload=function(){c=a.width;d=a.height;if(0==c||0==d){for(var e=null,g=document.getElementsByTagName("img"),f=0;f<g.length;f++)-1!=g[f].src.indexOf(".c.")&&(e=g[f]);null!=e&&(c=e.width,d=e.height,0==c&&(c=1*e.getAttribute("width")),0==d&&(d=1*e.getAttribute("height")))}if(0==c||0==d)d=c=300;e=document.title;g="";for(f=0;f<e.length;f++){var h=e.charAt(f);if("a"<=h&&"z">=h||"A"<=
h&&"Z">=h||"0"<=h&&"9">=h)g+=h}if(f=window.open("",g,"width="+(c+20)+",height="+(d+20)+",top=10,left="+(screen.width-c-60)+",resizable=yes,menubar=yes,toolbar=no,statusbar=no,locationbar=no,directories=no"))f.document.close(),f.document.open(),f.document.write("<html><head><title>L\u00f6sung: "+document.title+"</title></head>"),f.document.write("<body bgcolor=white>"),f.document.write('<image src="'+b.name+'" style="max-width:100%; height:auto;">'),f.document.write("</body></html>"),f.document.close(),
f.focus()}};ojx.initTabs=function(a,b){var c;(c=document.getElementById(a+"-0"))&&ojx.show(c);for(var d=1;10>=d;d++){if(c=document.getElementById(a+"-"+d))c.className=b+"-c";(c=document.getElementById(a+"-"+d+"-hdr"))&&ojx.hide(c)}b=ojx.getCookie(a);null==b&&(b=1);document.getElementById(a+"-"+b)||(b=1);ojx.execTabs(a,b)};
ojx.execTabs=function(a,b){var c=document.getElementById(a+"-"+b);if(!c)return!1;for(var d=1;10>=d;d++)if(c=document.getElementById(a+"-"+d)){var e=c.className.substring(0,c.className.indexOf("-")),g=document.getElementById(a+"-"+d+"-tab");d==b?(g&&(g.className=e+"-a"),ojx.show(c)):(g&&(g.className=e+"-i"),ojx.hide(c))}ojx.setCookie(a,b,30);ojx.resizeAllFramesDelayed();parent&&parent.ojx.resizeAllFramesDelayed();return!0};
ojx.initMenu=function(a){ojx.app&&(a||(a="menu"),document.getElementById(a+"-0")&&ojx.execMenu(a))};
ojx.execMenu=function(a,b){if(!ojx.app)return!1;a||(a="menu");var c=document.getElementById(a+"-0");if(!c)return!1;ojx.hide(c);b||(b=1);c=document.getElementById(a+"-"+b);if(!c)return!1;for(var d=1;10>=d;d++)if(c=document.getElementById(a+"-"+d))d==b?(ojx.show(c),ojx.menu=b):ojx.hide(c);a=document.getElementById(a+"-"+b+"-hdr");b=document.getElementById("ut");a&&b&&(b.innerHTML=a.innerHTML,ojx.hide(a));ojx.resizeAllFramesDelayed()};
ojx.showMenu=function(a){a||(a="menu");var b=document.getElementById(a+"-0");if(!b)return!1;if(ojx.isVisible(b))ojx.hide(b);else{ojx.show(b);var c=document.activeElement,d=function(a){c.contains(a.target)||ojx.hide(b);document.removeEventListener("click",d)};document.addEventListener("click",d)}};ojx.hideMenu=function(a,b){a||(a="menu");a=document.getElementById(a+"-0");if(!a)return!1;document.getElementById(b)&&(window.location="#"+b);ojx.hide(a)};
ojx.swipedetect=function(a,b){var c,d,e,g,f,h,k,l=b||function(a){};a.addEventListener("touchstart",function(a){var b=a.changedTouches[0];f="none";dist=0;c=b.pageX;d=b.pageY;k=(new Date).getTime();a.preventDefault()},!1);a.addEventListener("touchmove",function(a){a.preventDefault()},!1);a.addEventListener("touchend",function(a){a=a.changedTouches[0];e=a.pageX-c;g=a.pageY-d;h=(new Date).getTime()-k;300>=h&&(66<=Math.abs(e)&&33>=Math.abs(g)?f=0>e?"left":"right":66<=Math.abs(g)&&33>=Math.abs(e)&&(f=0>
g?"up":"down"));l(f)},!1)};ojx.swipeinit=function(a,b,c){a||(a=document.body);b||(b="prev");c||(c="next");ojx.swipedetect(a,function(a){var d;"right"==a&&(d=document.getElementById(b))&&location.replace(d);"left"==a&&(d=document.getElementById(c))&&location.replace(d)})};ojx.registerPWA=function(){"serviceWorker"in navigator&&navigator.serviceWorker.register("pwaworker.js").then(function(){console.log("PWA: registered")})};
ojx.showPage=function(a,b){a||(a="page");b||(b=1);for(var c=1;10>=c;c++){var d=document.getElementById(a+"-"+c);d&&(c==b?ojx.show(d):ojx.hide(d))}a=document.getElementById(a+"-"+b+"-hdr");b=document.getElementById("ut");a&&b&&(b.innerHTML=a.innerHTML,ojx.hide(a));ojx.resizeAllFramesDelayed()};
ojx.modifyLinks=function(){if(ojx.pwa)for(var a=document.getElementById("aufgaben").querySelectorAll("a"),b=0;b<a.length;b++)-1!=a[b].href.indexOf(".a.htm")&&(a[b].setAttribute("href","javascript: void(0);"),a[b].setAttribute("onclick","ojx.sel("+a[b].innerHTML+");"))};ojx.sel=function(a){ojx.pwa&&(ojx.showPage("page",2),ojx.puzzle.sel(a))};
ojx.accordion=function(a,b){a=document.getElementById(a);b=document.getElementById(b);var c=a.innerHTML;ojx.isVisible(b)?(ojx.hide(b),c=c.replace("\u2227","\u2228")):(ojx.show(b),c=c.replace("\u2228","\u2227"));a.innerHTML=c;ojx.resizeAllFrames()};ojx.accordion2=function(a,b){a=document.getElementById(a);b=document.getElementById(b);var c=a.classList;ojx.isVisible(b)?(ojx.hide(b),c=c.replace("-cls","-opn")):(ojx.show(b),c=c.replace("-opn","-cls"));a.classList=c;ojx.resizeAllFrames()};
